antfu-collective/ni

package.json
pnpm-lock.yaml
src/agents.ts
src/detect.ts
src/utils.ts

Will be making a few more changes to my fork, but will PR in changes in case you want them.
My end goal is to support `ni --frozen --fallback npm` so that it can be used in arbitrary CI environments (eg. https://github.com/antfu/export-size-action/blob/main/src/size.ts#L29) while also improving user-friendliness via:
- Providing installation instructions if the detected agent is missing
- `--frozen` to fallback to normal install if no lock file is found (this might be unexpected behavior and might be worth adding explicitness for eg. `--frozen=safe`)
- `--fallback` flag to take precedent over `defaultAgent` (for CI envs)

feat: handle non-installed agent error

---

README.md
src/config.ts

Hi, I want to try `ni`, but I want to customize the path to the config file, for example `export NI_CONFIG_FILE="$XDG_CONFIG_HOME/ni/nirc"`

feat: custom rc path

---

src/agents.ts
src/config.ts
src/detect.ts
test/ni/yarn@berry.spec.ts

Previously #50 has added support for `packageManager` field, but it does not detect yarn 2+, which has different command arguments. This pr fixed that.
Yarn 2+ users are likely to stay at the `berry` version branch (as its doc suggested `yarn set version stable`), which means we can just maintain 2 versions of yarn (1 & berry) to support most of the users.
\[Help Wanted\] I myself do not use yarn because of yarn@1's lack of maintaining and yarn@berry's breaking node_modules (the node's convention of resolving modules). Therefore I hope some real yarn 2+ user could help reviewing this pr.
closes #25

feat: support yarn@berry

---

README.md

`Del` itself  is an alias and when working in a restricted PS environment or if the aliases have been altered already, `Del` could not work. Also added `-ErrorAction Ignore` to avoid failing if the `ni` alias doesn't exist.
The PS 7 command or both command sections could also be replaced by this, although the PS 7 command is more modern.

docs: Updated PowerShell comment

---

README.md

Updated the information for PowerShell, to not only remove the alias in the different PowerShell versions, but also to persist them in your PowerShell profile.
#81

docs: Updated PowerShell information in README

---

test/na/yarn@berry.spec.ts
test/nr/yarn@berry.spec.ts
test/nu/yarn@berry.spec.ts

This adds missing three yarn berry tests. Even `na` and `nr` are the same as yarn classic, `nu` is quite different 😄.

test: add missing yarn berry test

---

src/parse.ts
src/runner.ts

fix: display help before detect agent

---

src/agents.ts
test/nx/bun.spec.ts
test/nx/npm.spec.ts
test/nx/pnpm.spec.ts
test/nx/yarn.spec.ts
test/nx/yarn@berry.spec.ts

As of bun@v0.4.0, bun now has `bunx` which is a lot faster than `npx` so this PR adds that feature

feat: add bunx as execute in bun

---

README.md
bin/nix.mjs
package.json
src/commands/nix.ts
src/commands/nx.ts
src/parse.ts
src/runner.ts
test/nx/bun.spec.ts
test/nx/npm.spec.ts
test/nx/pnpm.spec.ts
test/nx/yarn.spec.ts
test/nx/yarn@berry.spec.ts

Due to a conflict with the existing tool [nx](https://nx.dev/), a pretty popular tool, we find it better to rename `nx` to `nix` for compatibility.
Everyone can still create an alias if they still want to use `nix` as `nx`.
#118

feat: rename nx to nix

---

.gitignore
.vscode/settings.json
src/parse.ts
src/runner.ts

feat: add error message for unsupported commands/package managers

---

src/utils.ts

On [my windows install](https://github.com/Atlas-OS/Atlas), the `help` command doesn't exist.
This will throw an error every time I run `ni` or `nr`
```
'help' is not recognized as an internal or external command,
operable program or batch file.
```
The detection with `where` should be sufficient anyway.

fix: windows cmd detection

---

src/utils.ts

- Optimize the code performance by using more efficient functions.
- Use `splice` method in `remove` function to remove an element from an array instead of creating a new one.
- Use `slice` method in `exclude` function to make a shallow copy of the original array instead of modifying it directly.
- Use `which.sync` method in `cmdExists` function to check if a command exists instead of creating a child process and executing a command.
The original code had some performance issues due to the use of inefficient functions. By optimizing the code, we can improve its performance and make it more efficient.

perf: optimize code performance

---

README.md

fix: 1. The newly added $profileEntry content did not start on a new line, causing it to be appended twice to the ps1 file. 2. Not specifying the file encoding resulted in garbled content when appending.
1. The newly added $profileEntry content did not start on a new line, causing it to be appended twice to the ps1 file.
2. Not specifying the file encoding resulted in garbled content when appending.

docs: update powershell instructions

---

src/runner.ts

This PR adds `ni -V` flag which shows agent and node versions additionally to ni version
```
PS D:\repos\ni> ni -V
@antfu/ni v0.21.6
node      v20.5.1
pnpm      v8.6.12
npm -g    v9.8.0
```
I wanted so see the agent and node versions, same as `tsx` does with node version
```
PS D:\repos\ni> tsx -v
tsx v3.12.7
node v20.5.1
```
none
- not sure about flag name
- maybe a long flag name alternative is required
- this was not added to just `--version` because it has another format *and takes a few second to run*, 
- maybe add versions of something else? (likely out-of-scope)
- I've made text appear in columns because I like it, but you may close to remove it
- edit: config file location also can be useful as well

feat: add flag to show agent versions

---

src/config.ts
src/detect.ts
test/fixtures/packager/pnpm-version-range/package.json

Issue from https://github.com/ant-design/ant-design/pull/45327?notification_referrer_id=NT_kwDOAcKkeLM4MDQzMTU0MTMwOjI5NTMzMzA0#issuecomment-1767488121
Corepack has supported a range version for a long time. You can see https://github.com/nodejs/corepack/pull/136

feat: support detect the range version of packageManager

---

test/programmatic/__snapshots__/detect.spec.ts.snap
test/programmatic/detect.spec.ts

`test/programmatic/detect.spec.ts` is supposed to run _matrix testing of: fixtures x agents_, however `fixture` is not passed down. As a result, the test runs on `lockfile` twice.
None
None

fix: packager detect tests are not running

---

README.md

surround with code block, so can copy command with one click.
Make install command block more convenient by surrounding it with code block. Now can copy command with one click.
screenshot (or go to https://github.com/hms5232/ni/tree/hms5232-patch-1 preview):

docs: allow copy for install command

---

package.json
pnpm-lock.yaml
src/detect.ts
src/runner.ts
test/programmatic/runCli.spec.ts

Replace `execa` w/ `ezspawn`, see also https://github.com/antfu-collective/taze/pull/115
N/A
The PR reduces the final dist size by 36 KiB:
**Previous**
**After**

refactor: replace `execa` with `ezspawn`

---

README.md
src/agents.ts
test/ni/bun.spec.ts
test/programmatic/__snapshots__/runCli.spec.ts.snap

Fixed incorrect commands related to the `bun` frozen-lockfile option.
The original implementation incorrectly used `bun install --no-save` for the frozen-lockfile option. The correct command should be `bun install --frozen-lockfile`, as per the `bun` documentation.
The `bun` documentation under the bun install section [here](https://bun.sh/docs/cli/install#production-mode) states:
> For reproducible installs, use `--frozen-lockfile`. This will install the exact versions of each package specified in the lockfile. If your `package.json` disagrees with `bun.lockb`, Bun will exit with an error. The lockfile will not be updated.
> $ bun install --frozen-lockfile
Additionally, the lockfile section [here](https://bun.sh/docs/install/lockfile) mentions:
> Can I opt out?
> To install without …

fix(bun): incorrect bun frozen-lockfile command

---

src/agents.ts

Even though the Bun documentation says that the command `bunx` is just an alias of `bun x`, in reality `bunx` often doesn't work when `bun x` does. I suggest using `bun x` every time.
No issue was created
To demonstrate the difference between `bunx` and `bun x`, just try to init a Nuxt project with each. `bunx` fails while `bun x` successfully runs.
This may not be the case with all operating systems and/or all Bun installation methods. I'm using WIndows 11 and Bun was installed via npm.

fix: `bun x` instead of `bunx`

---

src/runner.ts

The if-statement used to print version info seems duplicated from the previous one, making it unnecessary.

chore(runner): delete useless if-statement used to print version info

---

src/commands/nr.ts

First of all, I would like to express my gratitude for developing ni, which I really enjoy using. During my usage, I wished for a feature to repeat the last command, and after reviewing the code, I discovered that this feature already exists, but it does not function on several of my devices.
Eventually, I found that the `suggest` section of the code executes once upon initial display, at which time the input is empty, leading to a display order that is inconsistent with expectations.

fix: nr command lastRunCommand not work

---

package.json
pnpm-lock.yaml

Updated the version of `package-manager-detector` so that `ni` works in Bun projects with the new `text-lockfile`.
Mainly for this PR: https://github.com/antfu-collective/package-manager-detector/pull/38

chore: bump ` package-manager-detector` to `v0.2.8`

---

README.md
src/parse.ts
test/ni/bun.spec.ts
test/ni/npm.spec.ts
test/ni/pnpm.spec.ts
test/ni/yarn.spec.ts
test/ni/yarn@berry.spec.ts

Add support for installing only production dependencies by passing `-P` flag.
```
ni -P
```
This allows for installing only the production dependencies to allow more lightweight runtimes. See #250 for more details.
fixes #250
Not sure how much value the comment
```ts
// npm use `--omit=dev` instead of `--production`
```
is adding, but I included it for symmetry with the previous comment above.

feat: add support for production install

---

README.md
package.json
pnpm-lock.yaml
src/commands/nci.ts
test/ni/bun.spec.ts
test/ni/npm.spec.ts
test/ni/pnpm.spec.ts
test/ni/yarn.spec.ts
test/ni/yarn@berry.spec.ts

Adds support for installing only production dependencies while adhering to lock file specification and ensuring it is consistent with package.json
Allows user to call `nci -P` or `ni --frozen -P` to do so.
> [!WARNING]  
> `pnpm-lock.yaml` points to a linked version of `package-manager-detector`, which I used locally to develop. https://github.com/antfu-collective/package-manager-detector/pull/40 should be merged and released first, and the version of the new release should be used as a dependency before merging and releasing changes from this PR.
#254 and to extent #250 (as the seed of the idea)
resolves #254 
Builds are failing due to the usage of linking mentioned in the warning section above - `nr build` runs OK locally with `package-manager-detector` linked to …

feat: support frozen production install

---

README.md

`ni` already supports bun's new text-based lockfile format (`bun.lock` instead of `bun.lockb`) since upgrading package-manager-detector to [v0.2.8](https://github.com/antfu-collective/package-manager-detector/releases/tag/v0.2.8). this PR only adds this info into the readme.
#249

docs: add info about `bun.lock`

---

src/commands/nr.ts

我从 codesanbox 下载 zip 到本地后，直接执行 `nr`，控制台什么都没有，虽然这个场景会很小，但是至少可以对其进行一些补充。

chore: improve script retrieval and add warning for empty scripts

---

src/environment.ts
src/runner.ts
test/runner/runCli.test.ts

What:
Add a way to turn on `autoInstall` for all commands.
This is a non breaking change that enable users to do something like this.
```bash
NI_AUTO_INSTALL=true nr <my_command>
```
It should work in all commands, but I need this feature specifically in `nr` (to run `nr` in CI without installing the package manager, as I don't know which one will be used)
How:
A new "module" to detect environment variables are added and used in the runner.
The runner now merges the options provided as input with the environment options prioritising the provided input.
I added a little bit of tests also for the runner file, It's not currently testing everything, but considering that there were no test prior to this, it's a starting point.
fix https://github.com/antfu-collective/ni/issues/247
I'm not …

feat: enable auto-install to be used in all commands (not only `nci`)

---

README.md
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
src/commands/nr.ts
src/monorepo.ts
src/package.ts
src/parse.ts
src/runner.ts

This PR adds **monorepo support for the `nr` command**, enabling users to interactively select which package to run scripts from in multi-package repositories.
**Key changes:**
When multiple packages are detected, shows a searchable/filterable prompt (powered by `fzf`) displaying package names and descriptions. Automatically falls back to single-package behavior when only one package is found
- Moved `tinyglobby` from dev to production dependencies for package discovery
- Added `promptSelectPackage()` function that returns the appropriate `RunnerContext` for the selected package
- Modified `readScripts()` to be async and integrate with package selection
**Impact scope:**
- Affects `nr` command behavior in monorepo environments

feat(nr): support -p flag to filter monorepo package in completion

---

src/runner.ts
src/utils.ts

As the linked issue, long-running process won't stop at once after you send `SIGINT`, it caused by tinyexec's design, the children processes of the main process won't stop and it may interference console interaction.
As a result, we need to kill the children processes to avoid more unexpected output, I used to try making a [`tree-kill`](https://github.com/pkrumins/node-tree-kill) function to solve it, but luckily, nodejs provides `detached` options to do the similar thing with one line's code
Close #244
**~this issue killed half my brain cells lol~**
⬆️ About it's reason
You cannot use `pnpm dev` command to test the solution because `pnpm` may process the `SIGINT`, maybe influenced the output log result
You also cannot use `tsx` commands like `npx tsx src/commands/ni.ts` to test the …

fix(runner): wait for child process before exit on `SIGINT`
