src/commands.ts, src/detect.ts, src/ni.ts, src/runner.ts, src/utils.ts
As per conversation from https://github.com/antfu/ni/pull/5
=> feat(ni): flag --freeze-if-present

package.json, pnpm-lock.yaml, src/commands.ts, src/detect.ts, src/nci.ts, src/runner.ts
As per https://github.com/antfu/ni/pull/5
Here's the agent install prompt feature.
`nci` PR https://github.com/privatenumber/ni/pull/2
=> feat: agent install prompt & `nci`

bin/nx.js, package.json, src/agents.ts, src/commands.ts, src/nx.ts
I had an issue running it in dev mode, so I can't guarantee that it works. Would you be able to test it on your machine?
Also, prettier automatically formatted the files I changed so apologies for the large diff.
If all is good, then this closes #13
=> feat: add nx

.gitignore, package.json, pnpm-lock.yaml, src/runner.ts, src/utils.ts
- [Volta](https://volta.sh/)
- [Blog - Command Spotlight: volta run](https://blog.volta.sh/2020/11/25/command-spotlight-volta-run/)
- [Guide - volta run](https://docs.volta.sh/reference/run)
#43
=> fix: Respect volta npm and yarn paths

README.md, src/agents.ts, test/ni/pnpm.spec.ts
- Keep the same as the official document
=> chore: update some commands for pnpm

README.md, src/agents.ts
Probably makes sense to point out the difference between Yarn 1 and Yarn Berry (~~I choose "Yarn 2+" here to be less confusing for unfamiliar people~~), kind of like a cheatsheet.
=> docs: add equivalent commands for Yarn berry

src/agents.ts
Update install page links
None
None
=> docs: update install page links

src/commands/nihao.ts, src/parse.ts
feat(argument): -help ( display ni's brief help document )
#101
=> feat: `--help` argument

README.md
As a fact, eslint is a good thing ;)
BTW,
I'm also highly inspired by [antfu/eslint-config](https://github.com/antfu/eslint-config) , that's awesome!
It's too late for me to meet [ni](https://github.com/antfu/ni), so great,
until which I'd been aliasing `ni=pnpm` myself, and that could make troubles sometimes.
=> docs: never recommend to uninstall eslint ;)

package.json, pnpm-lock.yaml, src/commands/nr.ts
Support fuzzy match. `unit` => `test:unit` and ignores case
closes #112
=> feat(nr): support fuzzy matching

package.json
If you just import this package, typescript will complain about its types.
=> fix: types when using package programmatically

src/agents.ts
=> fix(yarn): use npx for execute(yarn 1)

README.md
=> chore: update readme for pnpm@7

src/detect.ts
=> feat: optional detect argument

src/index.ts
=> feat: export agents

README.md
`bunx` is implemented but README still says not available for Bun.
=> docs: add bunx to README

src/config.ts
It looks like a regular expression error.
=> fix: regex typo

README.md
Update readme to reflect https://github.com/antfu/ni/pull/167
=> docs: update `bun update` command

README.md
hello @antfu, i just add the documentation about global flags like **-C**, **-v, --version**, **-h, --help**, and **?**.
i hope this PR can help people who want to use the library.
thanks
none
none
=> docs: add global flags documentation

src/config.ts
=> fix: .nirc may not exist

src/config.ts, test/programmatic/__snapshots__/runCli.spec.ts.snap
correctly override local agent
fixes #187
=> fix: correctly override local agent

README.md
=> docs: set custom config file path in PowerShell

README.md
Add asdf install instructions to readme, I added them more to the bottom for now as it's 3rd party maintained and I wasn't sure how you'd prefer it, but we could move it around and of course change wording
as discussed in https://github.com/antfu/ni/issues/198#issuecomment-1960168137
=> docs: add asdf plugin instructions

README.md, src/config.ts, test/config/.nirc, test/config/config.test.ts
Adds a option to use environment variables for config which will overwrite a file config. I also added a couple of tests and the relevant docs changes.
Closes #158
=> feat: support environment variables for ni config

package.json, pnpm-lock.yaml, src/commands/ni.ts, src/fetch.ts, src/runner.ts, src/utils.ts
This PR replaces `kleur` with `yoctocolors`, will go to my other PR (not to main directly): https://github.com/antfu-collective/ni/pull/220
=> chore: replace `kleur` with `yoctocolors`

package.json
=> chore: bump `pnpm` to `v9.7.1`

.github/workflows/publish-commit.yml, package.json
This PR adds [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) to allow test releases on CI: will generate a publish on every commit on this repo on main or any PR including `/pkg-pr-new` comment. We can later filter PR title etc...
/cc @Aslemammad
=> chore: add `pkg.pr.new`

src/commands/nr.ts
When searching for 'build' in nr, the first item displayed is 'prepublishOnly'.
Expected:
=> feat(nr): add sorting configuration option to Fzf

README.md
This PR  includes a reference to package-manager-detector and its commands (changing the existing commands link in the `How` section, there current link is wrong)
=> docs: update `How` section

src/runner.ts, test/programmatic/__snapshots__/runCli.spec.ts.snap, test/programmatic/runCli.spec.ts
debug `?` should directly output the command text
fix #266
close #267
=> fix!: improve debug logging format for command execution

.github/workflows/publish-commit.yml
=> ci: bump actions checkout to v4

pnpm-workspace.yaml
update package-manager-detector to 1.3.0 to detect pnpm-workspace.yml
fix https://github.com/antfu-collective/ni/issues/273
=> feat: detect pnpm-workspace.yaml

README.md
Hi,
I see that NI supports Deno, but it is not mentioned in the README. I decided to fix this :)
Have a good day,  
Andrew
=> Mention Deno in README

README.md, src/commands/nr.ts, src/completion.ts, src/package.ts
For zim:fw, which is a zsh package manager
fixes #284
=> feat: support zsh completion
